services:
  hugo-static-website:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/hugo-static-website
      dockerfile: customize-example.Dockerfile
    command: >
      hugo server
      --baseURL http://127.0.0.1:1313
      --bind 0.0.0.0
      --buildDrafts
    init: true
    ports:
      - "127.0.0.1:1313:1313"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - ./code-stubs/hugo-static-website:/workspace
    working_dir: /workspace
