name: publish-docker-images
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
on:
  push:
    branches:
      - main
    tags:
      - hugo-*
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      #
      # Build image
      - name: Build the image
        # timeout-minutes: 16
        run: |
          docker buildx build\
           --platform linux/amd64,linux/arm64\
           --tag=local.local/no-name/hugo-static-website:HEAD\
           Dockerfile.d/hugo-static-website/
